use @gcloud/datastore instead to reduce dependencies
fabito/botkit-storage-datastore pull request #3
Opened 2018-03-23 05:48 UTC by tonymet

* using @google-cloud/datastore reduced the overall dependencies needed, meaning faster install and smaller node_modules
* updated test

### Test Results

```
➜  botkit-storage-datastore git:(feature/smaller-dependencies) npm test

  Datastore
    init
      ✓ should require a config
      ✓ should require projectId
      ✓ should initialize datastore with projectId
    key
      ✓ should use custom kind
    get
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    get from namespace
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    save
      ✓ should call datastore save
    save into namespace
      ✓ should call datastore save
    all
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    all from namespace
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    key
      ✓ should use custom kind
    get
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    get from namespace
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    save
      ✓ should call datastore save
    save into namespace
      ✓ should call datastore save
    all
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    all from namespace
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    key
      ✓ should use custom kind
    get
      ✓ should get entity
      ✓ should handle non existent entity
[]
      ✓ should call callback on error
    get from namespace
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    save
      ✓ should call datastore save
    save into namespace
      ✓ should call datastore save
    all
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    all from namespace
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error

  48 passing (806ms)

=============================================================================
Writing coverage object [/mnt/c/Users/AnthonyMetzidis/sotion/botkit-storage-datastore/coverage/coverage.json]
Writing coverage reports at [/mnt/c/Users/AnthonyMetzidis/sotion/botkit-storage-datastore/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 100% ( 35/35 )
Branches     : 100% ( 24/24 )
Functions    : 100% ( 10/10 )
Lines        : 100% ( 35/35 )
```

2018-03-27 19:08 UTC, tonymet commented
@fabito what do you think about this change? i think it may be an easy merge once travis' config is updated using the `migration` above to restore code coverage.

2018-04-10 21:15 UTC, tonymet commented
@fabito any way i can help get this one merged?

2018-04-10 21:25 UTC, fabito commented
Have you seen my last comment ?

On Tue, Apr 10, 2018 at 6:15 PM Tony Metzidis <notifications@github.com>
wrote:

> @fabito <https://github.com/fabito> any way i can help get this one
> merged?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fabito/botkit-storage-datastore/pull/3#issuecomment-380248975>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAS1hYNJnWLEFCPVMyuPFQi-wfGmmy-6ks5tnSDbgaJpZM4S4NRQ>
> .
>

2018-04-10 21:29 UTC, tonymet commented
i'm sorry no there doesn't seem to be any comments from you on my view of the PR

2018-04-10 22:16 UTC, tonymet commented
@fabito can you re-share your previous comment?

2018-04-11 01:18 UTC, fabito requested changes

2018-04-11 01:18 UTC, fabito commented on tests/it.js
> +	projectId: process.env.projectId,
@tonymet ,

I don't know exactly why are you pulling the the `projectId` from the environment variables, but I think you could leave the former value as fallback. Something like this:

`projectId: process.env.projectId || 'myproject'`

What do you think ?

2018-04-11 01:38 UTC, tonymet commented on tests/it.js
> +	projectId: process.env.projectId,
great suggestion I'll fix.  I added the env config to allow the tests to be run against any GCP project ID without a code-change

2018-04-12 04:09 UTC, tonymet commented
@fabito thanks for the feedback i've added the default value.

2018-04-12 10:07 UTC, fabito approved these changes

2018-04-12 10:08 UTC, merged

2018-04-12 10:09 UTC, fabito commented
@tonymet  thanks a lot for the PR!